github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories:   ["docker.io/paketobuildpacks/maven","gcr.io/paketo-buildpacks/maven"]
  register:       true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.GCR_PUSH_BOT_JSON_KEY }}
- registry: docker.io
  username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
  password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
- name:            Maven 3
  id:              maven
  uses:            docker://ghcr.io/paketo-buildpacks/actions/maven-dependency:main
  version_pattern: "^3\\.[\\d]+\\.[\\d]+"
  with:
    uri:           https://repo1.maven.org/maven2
    group_id:      org.apache.maven
    artifact_id:   apache-maven
    classifier:    bin
    packaging:     tar.gz
    version_regex: "^3\\.[\\d]+\\.[\\d]+$"
- name:            Maven 4
  id:              maven
  uses:            docker://ghcr.io/paketo-buildpacks/actions/maven-dependency:main
  version_pattern: "^4\\.[\\d]+\\.[\\d]+"
  with:
    uri:           https://repo1.maven.org/maven2
    group_id:      org.apache.maven
    artifact_id:   apache-maven
    classifier:    bin
    packaging:     tar.gz
    version_regex: "^4\\.[\\d]+\\.[\\d]+-.*$"
- name: Maven Daemon 0
  id:   mvnd
  uses: docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  version_pattern: "^0\\.[\\d]+\\.[\\d]$"
  with:
    owner: apache
    repository: maven-mvnd
    glob: mvnd-.+-linux-amd64.zip
    tag_filter: "^0\\.[\\d]+\\.[\\d]$"
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
- name: Maven Daemon 1
  id:   mvnd
  uses: docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  version_pattern: "^1\\.[\\d]+\\.[\\d](?:-.*)?$"
  with:
    owner: apache
    repository: maven-mvnd
    glob: mvnd-.+-linux-amd64.zip
    tag_filter: "^1\\.[\\d]+\\.[\\d](?:-.*)?$"
    token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}
